[tools]
deno = 'latest'

[env]
'_'.path = ['bin']

[tasks.install]
description = "Install to global bin"
run = "deno install -fgA index.ts --name x --config deno.json"

[tasks.dev]
description = "Run with args when developing"
run = "deno run -A index.ts {{arg(name='rest',var=true)}}"
